runtime: python311

# App Engine 설정
instance_class: F2

# 환경 변수 (필요시 추가)
# env_variables:
#   OPENAI_API_KEY: "your-api-key"

# 자동 스케일링 설정
automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.7
  max_concurrent_requests: 80
  max_pending_latency: 30s
  min_pending_latency: 5s

# 엔트리포인트
entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker surgiform.deploy.server:app --bind :$PORT

# 핸들러
handlers:
- url: /.*
  script: auto
  secure: always

# 리소스 설정
resources:
  cpu: 2
  memory_gb: 2.5
  disk_size_gb: 10

# 헬스체크
readiness_check:
  path: "/health"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300

liveness_check:
  path: "/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2