# Cloud Build 설정 파일
steps:
  # Docker 이미지 빌드
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/surgiform-backend:$COMMIT_SHA', '.']
    dir: 'surgiform-backend'
  
  # 최신 태그 추가
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'gcr.io/$PROJECT_ID/surgiform-backend:$COMMIT_SHA', 'gcr.io/$PROJECT_ID/surgiform-backend:latest']
  
  # Container Registry에 푸시
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/surgiform-backend:$COMMIT_SHA']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/surgiform-backend:latest']
  
  # Cloud Run 배포
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'surgiform-backend'
      - '--image=gcr.io/$PROJECT_ID/surgiform-backend:$COMMIT_SHA'
      - '--region=asia-northeast3'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=2Gi'
      - '--cpu=2'
      - '--max-instances=10'
      - '--min-instances=1'

# 빌드 타임아웃 설정
timeout: 1200s

# 이미지 목록
images:
  - 'gcr.io/$PROJECT_ID/surgiform-backend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/surgiform-backend:latest'